 on:
   push:
     branches:
       - master
 name: release
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2
         id: release
         with:
           command: release-pr
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: simple
       - run: echo $OUT
         env:
           OUT: ${{ toJson(steps.release.outputs) }}
       - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
         if: ${{ steps.release.outputs.release_created }}
       - run: git status
         if: ${{ steps.release.outputs.release_created }}
