 on:
   push:
     branches:
       - master
 name: release
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2
         id: release
         with:
           command: release-pr
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: simple
       - run: echo $OUT
         env:
           OUT: ${{ toJson(steps.release.outputs) }}
       - uses: actions/checkout@v2
         with:
           persist-credentials: false
       - name: git
         run: |
           # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
           git --version
           git config user.name "GitHub Actions Bot"
           git config user.email "kb@example.com"
           git status
           touch hello1
           git add hello1
           git commit -m 'fix: hello should loop'
           git push
       - run: git status
         if: ${{ steps.release.outputs.release_created }}
